In [5]:
import numpy as np

In [7]:
# Creating a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


In [17]:
# arange() function
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# arange() function & stepsize
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# Creating a 2-dimensional array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [11]:
# Performing arithmetic operations
arr = np.array([1, 2, 3, 4, 5])
print(arr + 5)  # Output: [ 6  7  8  9 10]

[ 6  7  8  9 10]


In [13]:
# Using mathematical functions
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0
print(np.std(arr))   # Output: 1.4142135623730951

3.0
1.4142135623730951


In [15]:
# Broadcasting example
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
print(arr1 + arr2)
# Output:
# [[2 3 4]
#  [3 4 5]
#  [4 5 6]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [21]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
# rand
np.random.rand(5)

array([0.74124721, 0.78901521, 0.80596383, 0.71768545, 0.38160527])

In [29]:
np.random.rand(5,5)

array([[0.96769559, 0.82211313, 0.25194822, 0.2855468 , 0.96817071],
       [0.41400128, 0.75594797, 0.6325596 , 0.6727347 , 0.76962515],
       [0.05619813, 0.91093557, 0.54334933, 0.97732623, 0.01264014],
       [0.89072372, 0.60249073, 0.45393256, 0.35308948, 0.08949345],
       [0.62401228, 0.76079457, 0.51047594, 0.05130869, 0.31374597]])

In [33]:
# standard dist
np.random.randn(2)

array([-0.25482237,  0.40481339])

In [39]:
# rand int
arr = np.random.randint(0,50,10)
print(list(arr))

[48, 10, 47, 47, 6, 8, 17, 37, 3, 48]


In [45]:
# min
arr.min()

3

In [47]:
# max
arr.max()

48

In [49]:
# location of max
arr.argmax()

0

In [55]:
# recall how we did this randint above
# arr = np.random.randint(0,50,10)

# Importing randint directly from numpy.random

from numpy.random import randint
randint(2,10)

6